version: '3'
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
  tests: 
    container_name: tests
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    command: ['npm',"run","test"]